export class I9 {
  i9FormType: number = 1;
  "i9DetailsId": number;
  "lastName": string;
  "firstName": string;
  "middleInitial": string;
  "otherLastName": string;
  "address": string;
  "aptNumber": string;
  "cityOrTown": string;
  "state": string;
  "zipCode": string;
  "dateOfBirth": string;
  "usSsn": string;
  "email": string;
  "phoneNumber": string;
  "citizenOfUs": string;
  "hasCitizenOfUs": any;
  "nonCitizenNationalOfUs": string;
  "hasNonCitizenNationalOfUs": any;
  "lawfulPermanentResident": string;
  "hasLawfulPermanentResident": any;
  "lprAlienRegNoOrUscisNo": string;
  "alienAuthorizedToWork": string;
  "hasAlienAuthorizedToWork": any;
  "alienAuthorizationWorkExpirationDate": string;
  "alienRegNoOrUscisNo": string;
  "formI94AdmnNumber": string;
  "foreignPassportNumber": string;
  "countryOfIssuance": string;
  "employeeDetailsId": number;
  "dateOfBirthFormat": Date;
  "alienAuthorizationWorkExpirationDateFormat": Date;
  "status": string;
  "employeeDocumentUploadDetailsId": number;
  dateSubmitted: string;
  signatureOfTheEmployee: string;
  signatureFontOfTheEmployee: string = "inherit";
  preparedByEmployer: number;
  i9Status: string = null;
  action: string;
  preparerAndOrTranslatorCertification: String;
  signatureOfThePreparerOrTranslator: string;
  signatureFontOfThePreparerOrTranslator: string = "inherit";
  dateSubmittedPreparer: string;
  lastNamePreparer: string;
  firstNamePreparer: string;
  addressPreparer: string;
  cityOrTownPreparer: string;
  statePreparer: string;
  zipCodePreparer: string;
}
