export enum Modules {
  EMPLOYEES = "Employees",
  PROFILE = "Profile",
  DEPARTMENTS = "Departments",
  DESIGNATIONS = "Designations",
  COMPANY = "Company",
  PROJECTS = "Projects",
  DOCUMENTS = "Documents",
  ORGANIZATIONS = "Organizations",
  I9 = "I9",
  W4 = "W4",
  TIMESHEETS = "Timesheets",
  PAYSTUBS = "Paystubs",
  NOTES = "Notes",
  FEEDBACK = "Feedback",
  APPROVERS = "Approvers",
  INVOICES = "Invoices",
  PAYMENTS="Payments",
  MYDOCUMENTS='My Documents',
  CHECKLIST='Checklist'
}
